-- Reward/workshop bugfix, step 3/3: restore_workshop_reward — credits back
-- the reward-balance portion of a cancelled workshop booking.
--
-- NOT YET APPLIED. Run AFTER 20260912100100_claim_workshop_reservations_
-- reward.sql.
--
-- CORRECTED 2026-09-12 (production verification): reward_transactions.type
-- CHECK constraint only allows 'earned' | 'spent' | 'expired' | 'adjustment'
-- — the original version of this migration used 'refunded', which does not
-- exist and would have failed at runtime. Fixed to use 'earned', mirroring
-- refund_reward_for_order's own model (per the user's direct verification).
--
-- Consequence of using 'earned': reward_transactions_order_earned_unique
-- (migration 20260912090500 — unique on order_id where type='earned') allows
-- only ONE 'earned' row per order. finalize_reward_for_order() already owns
-- that row for a REAL cashback-earning order (cake-only / mixed) — but never
-- inserts one for a workshop-only order, because its v_products sum
-- excludes every workshop line (product <> 'workshop'), so v_earned is
-- always exactly 0 there and the insert is skipped entirely
-- (finalize_reward_for_order, `if v_earned > 0 then insert ...`). That
-- makes this function the SOLE owner of the 'earned' row for a workshop-
-- only order — and since the SAME reservation can be partially cancelled
-- several times (each its own workshop_cancellation_log row), this function
-- must ACCUMULATE onto that one row (ON CONFLICT ... DO UPDATE) rather than
-- insert a second one, which is what the code below does. It never touches
-- orders.reward_amount_earned or v_products, so no cashback is ever
-- generated by a restoration, by construction — cashback stays governed
-- solely by finalize_reward_for_order(), untouched by this file.
--
-- Why this can't just reuse refund_reward_for_order(): that RPC fires only
-- from trg_order_reward_status_change, on a whole-order orders.payment_status
-- -> 'refunded' transition — a transition cancel-workshop-seats never makes
-- (confirmed: neither cancel_workshop_seats() nor finalize_workshop_refund()
-- ever touches orders.payment_status, for a partial OR a full workshop
-- cancellation — and per the "no automatic PostFinance refund" policy,
-- cancel-workshop-seats no longer even attempts a cash refund itself, only
-- records what is DUE; see cancel-workshop-seats/index.ts). A workshop
-- cancellation also needs PER-SEAT, proportional restoration (some seats
-- cancelled, not the whole reservation, possibly across several separate
-- cancellations), which is a different granularity than a whole-order
-- refund. Hence a dedicated, narrower RPC instead of overloading or
-- duplicating that one.
--
-- Idempotency: keyed on workshop_cancellation_log.reward_amount_restored,
-- the same table/pattern already used for refund_amount_completed. Checked
-- and set inside the SAME row lock as the insert/accumulate below, so two
-- calls for the SAME log row (a genuine retry) can never restore reward
-- twice — the second call sees reward_amount_restored > 0 and no-ops.
--
-- 2026-09-12 (concurrency correction): p_amount is expected to be
-- workshop_cancellation_log.reward_amount_due for this log row — a figure
-- now computed ATOMICALLY by cancel_workshop_seats() itself, under the
-- reservation's row lock, at cancellation time (see
-- 20260912100300_cancel_workshop_seats_atomic.sql). This function no longer
-- has to (and cannot, on its own) guarantee the cumulative cash/reward split
-- across concurrent cancellations of the same reservation is correct — that
-- guarantee now lives entirely in cancel_workshop_seats()'s lock. This
-- function's own responsibility stays narrow and simple: given an already-
-- correct amount tied to a specific log row, credit it to the cagnotte
-- exactly once.

create or replace function public.restore_workshop_reward(
  p_log_id      uuid,
  p_customer_id uuid,
  p_order_id    uuid,
  p_amount      numeric
)
returns numeric
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_log    public.workshop_cancellation_log%rowtype;
  v_amount numeric(10,2) := round(coalesce(p_amount, 0), 2);
begin
  if p_customer_id is null then
    -- Reservation belongs to a guest checkout (no account) — no cagnotte to
    -- restore. Never raises: a guest workshop simply has nothing to do here.
    return 0;
  end if;

  if v_amount <= 0 then
    return 0;
  end if;

  select * into v_log
  from public.workshop_cancellation_log
  where id = p_log_id
  for update;

  if not found then
    raise exception 'Cancellation log % not found', p_log_id using errcode = 'P0002';
  end if;

  -- Idempotency: already restored for this exact cancellation -> no-op.
  if v_log.reward_amount_restored > 0 then
    return 0;
  end if;

  -- type='earned' is the only type that credits the cagnotte (verified
  -- production constraint: earned | spent | expired | adjustment). Accumulate
  -- onto the order's single allowed 'earned' row (reward_transactions_
  -- order_earned_unique) instead of inserting a second one — see the header
  -- comment above for why this row is always free for a workshop-only order.
  -- expires_at only ever extends (GREATEST), never shortens, an existing
  -- expiry on accumulation.
  insert into public.reward_transactions (
    customer_id, order_id, type, amount, remaining_amount, expires_at, note
  ) values (
    p_customer_id, p_order_id, 'earned', v_amount, v_amount,
    now() + interval '1 year',
    'Reward restored after workshop cancellation'
  )
  on conflict (order_id)
    where type = 'earned' and order_id is not null
    do update set
      amount           = public.reward_transactions.amount + excluded.amount,
      remaining_amount = public.reward_transactions.remaining_amount + excluded.amount,
      expires_at       = greatest(public.reward_transactions.expires_at, excluded.expires_at);

  update public.workshop_cancellation_log
  set reward_amount_restored = v_amount,
      updated_at = now()
  where id = p_log_id;

  perform public.recompute_reward_balance(p_customer_id);

  return v_amount;
end;
$$;

-- Explicit, itemised — never rely on default/inherited privileges for a
-- money-touching function. Matches every other workshop RPC in this repo
-- (cancel_workshop_seats, finalize_workshop_refund, claim_workshop_
-- reservations_batch): service_role only, PostgREST/anon/authenticated
-- clients can never call this directly.
revoke execute on function public.restore_workshop_reward(uuid, uuid, uuid, numeric) from public;
revoke execute on function public.restore_workshop_reward(uuid, uuid, uuid, numeric) from anon;
revoke execute on function public.restore_workshop_reward(uuid, uuid, uuid, numeric) from authenticated;
grant execute on function public.restore_workshop_reward(uuid, uuid, uuid, numeric) to service_role;
